// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvolxrrsbmekcaqvendx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2b2x4cnJzYm1la2NhcXZlbmR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY0ODI2OTQsImV4cCI6MjEwMjA1ODY5NH0.zlU6Cj-LQoqWJJ3Rn276jcFQuMitPIatkP-kSfOFp_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});